# Generated by Django 5.2 on 2025-04-25 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0003_category_product_categories'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
