# Generated by Django 5.2 on 2025-04-25 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0004_alter_category_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Categorie', 'verbose_name_plural': 'Categories'},
        ),
    ]
