# Generated by Django 5.2 on 2025-04-26 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0006_supplier_product_supplier'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('contact_person', models.CharField(blank=True, max_length=100, null=True)),
                ('supplier_type', models.CharField(blank=True, choices=[('distributeur', 'Distributeur'), ('fabricant', 'Fabricant'), ('revendeur', 'Revendeur')], max_length=50, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_terms', models.CharField(blank=True, max_length=100, null=True)),
                ('bank_account', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('region_served', models.CharField(blank=True, max_length=100, null=True)),
                ('supplier', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='details', to='ecom.supplier')),
            ],
            options={
                'verbose_name': 'Détail Fournisseur',
                'verbose_name_plural': 'Détails Fournisseurs',
            },
        ),
    ]
